export const EXECUTION_STATUS = {
  PENDING: "PENDING",
  STARTED: "STARTED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
  RUNNING: "RUNNING",
};

export const NODE_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
};
