CREATE SCHEMA IF NOT EXISTS tasks;
CREATE TABLE IF NOT EXISTS tasks.tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INT NOT NULL UNIQUE,
    CONSTRAINT user_id_fk FOREIGN KEY(user_id) REFERENCES users.users(id) ON DELETE CASCADE
);